/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coba;
import java.sql.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.JOptionPane;
/**
 *
 * @author user
 */
public class Frame extends javax.swing.JFrame {
    private DefaultTableModel Tabel;
    private String SQL;
    /**
     * Creates new form Frame
     */
    public void TampilData(){
        Tabel = new DefaultTableModel();
        Tabel.addColumn("Nama");
        Tabel.addColumn("NIS");
        Tabel.addColumn("Kelas");
        Tabel.addColumn("Jurusan");
        jTable1.setModel(Tabel);
        Connection con = COBA.getConnection();
        try{
            java.sql.Statement st = con.createStatement();
            SQL = "select * from ds";
            java.sql.ResultSet rs = st.executeQuery(SQL);
            while (rs.next()){
                Tabel.addRow(new Object[]{
                rs.getString("Nama"),
                rs.getString("NIS"),
                rs.getString("Kelas"),
                rs.getString("Jurusan")
            });
            }
        }catch (SQLException e){
            System.out.println(e.getMessage());
        }
    }
    public Frame() {
        initComponents();
        this.TampilData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel = new javax.swing.JLabel();
        Name1 = new javax.swing.JLabel();
        Name2 = new javax.swing.JLabel();
        Name3 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        NIS = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        New = new javax.swing.JButton();
        Save = new javax.swing.JButton();
        Edit = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        nKelas = new javax.swing.JComboBox<>();
        tKelas = new javax.swing.JTextField();
        nJurusan = new javax.swing.JComboBox<>();
        tJurusan = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biodata Siswa SMA");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(204, 102, 255));

        jLabel1.setFont(new java.awt.Font("Calibri", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("BIODATA SISWA SMA");

        jLabel.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel.setForeground(new java.awt.Color(255, 255, 255));
        jLabel.setText("Nama");

        Name1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Name1.setForeground(new java.awt.Color(255, 255, 255));
        Name1.setText("NIS");

        Name2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Name2.setForeground(new java.awt.Color(255, 255, 255));
        Name2.setText("Kelas");

        Name3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Name3.setForeground(new java.awt.Color(255, 255, 255));
        Name3.setText("Jurusan");

        Name.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        NIS.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        jTable1.setBackground(new java.awt.Color(255, 204, 255));
        jTable1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        New.setBackground(new java.awt.Color(204, 102, 255));
        New.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        New.setForeground(new java.awt.Color(255, 255, 255));
        New.setText("New");

        Save.setBackground(new java.awt.Color(204, 102, 255));
        Save.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Save.setForeground(new java.awt.Color(255, 255, 255));
        Save.setText("Save");
        Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveActionPerformed(evt);
            }
        });

        Edit.setBackground(new java.awt.Color(204, 102, 255));
        Edit.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Edit.setForeground(new java.awt.Color(255, 255, 255));
        Edit.setText("Edit");
        Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditActionPerformed(evt);
            }
        });

        Delete.setBackground(new java.awt.Color(204, 102, 255));
        Delete.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        Delete.setForeground(new java.awt.Color(255, 255, 255));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        nKelas.setBackground(new java.awt.Color(204, 102, 255));
        nKelas.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nKelas.setForeground(new java.awt.Color(255, 255, 255));
        nKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IPA1", "IPA2", "IPA3", "IPA4", "IPA5" }));
        nKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nKelasActionPerformed(evt);
            }
        });

        tKelas.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        nJurusan.setBackground(new java.awt.Color(204, 102, 255));
        nJurusan.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        nJurusan.setForeground(new java.awt.Color(255, 255, 255));
        nJurusan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "IPA", "IPS" }));
        nJurusan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nJurusanActionPerformed(evt);
            }
        });

        tJurusan.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Name3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Name2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Name1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tJurusan, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(nKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tKelas))
                            .addComponent(NIS)
                            .addComponent(Name))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Edit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Save, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(New, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(New))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name1)
                    .addComponent(NIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Save))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name2)
                    .addComponent(Edit)
                    .addComponent(nKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Name3)
                    .addComponent(Delete)
                    .addComponent(nJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tJurusan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int baris = jTable1.getSelectedRow();
        Name.setText(Tabel.getValueAt(baris,0).toString());
        NIS.setText(Tabel.getValueAt(baris,1).toString());
        tKelas.setText(Tabel.getValueAt(baris, 2).toString());
        tJurusan.setText(Tabel.getValueAt(baris, 3).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    private void SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveActionPerformed
        try{
            Connection con = COBA.getConnection();
            PreparedStatement st = con.prepareStatement("insert into ds(NIS, Nama, Kelas, Jurusan) values(?,?,?,?)");
            st.setString(1, Name.getText());
            st.setString(2, NIS.getText());
            st.setString(3, tKelas.getText());
            st.setString(4, tJurusan.getText());
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Sudah Disimpan", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();
        }catch (SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_SaveActionPerformed

    private void EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditActionPerformed
        try{
            Connection con = COBA.getConnection();
            PreparedStatement st = con.prepareStatement("Update ds set Nama=?, Kelas=?, Jurusan=? where NIS=?");
            st.setString(1, Name.getText());
            st.setString(2, NIS.getText());
            st.setString(3, tKelas.getText());
            st.setString(4, tJurusan.getText());
            st.executeUpdate();
            JOptionPane.showMessageDialog(null, "Data Berhasil Diubah", "Pesan", JOptionPane.INFORMATION_MESSAGE);
            TampilData();
        }catch (SQLException e){
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_EditActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        Connection con = COBA.getConnection();
        int confirm = JOptionPane.showConfirmDialog(null, "Hapus Data?", "Konfirmasi", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (confirm == 0){
            try{
                java.sql.PreparedStatement st = con.prepareStatement("delete from ds where NIS ='" + NIS.getText() + "'");
                st.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Sudah Dihapus", "Pesan", JOptionPane.INFORMATION_MESSAGE);
                TampilData();
                Name.setText("");
                NIS.setText("");
                tKelas.setText("");
                tJurusan.setText("");
            }catch(SQLException e){
                JOptionPane.showMessageDialog(null, "Gagal Proses" + e.getMessage(), "Pesan", JOptionPane.ERROR_MESSAGE);
            }
        }
    }//GEN-LAST:event_DeleteActionPerformed

    private void nKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nKelasActionPerformed
        String Kelas;
        Kelas = (String)nKelas.getSelectedItem();
        tKelas.setText(Kelas);
        if (nJurusan.getSelectedItem().equals("IPA")){
            nKelas.removeAllItems();
            nKelas.addItem("IPA1");
            nKelas.addItem("IPA2");
            nKelas.addItem("IPA3");
            nKelas.addItem("IPA4");
            nKelas.addItem("IPA5");
        }
        else if (nJurusan.getSelectedItem().equals("IPS")){
            nKelas.removeAllItems();
            nKelas.addItem("IPS1");
            nKelas.addItem("IPS2");
            nKelas.addItem("IPS3");
            nKelas.addItem("IPS4");
            nKelas.addItem("IPS5");
        }
    }//GEN-LAST:event_nKelasActionPerformed

    private void nJurusanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nJurusanActionPerformed
        String Jurusan;
        Jurusan = (String)nJurusan.getSelectedItem();
        tJurusan.setText(Jurusan);
    }//GEN-LAST:event_nJurusanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Edit;
    private javax.swing.JTextField NIS;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel Name1;
    private javax.swing.JLabel Name2;
    private javax.swing.JLabel Name3;
    private javax.swing.JButton New;
    private javax.swing.JButton Save;
    private javax.swing.JLabel jLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JComboBox<String> nJurusan;
    private javax.swing.JComboBox<String> nKelas;
    private javax.swing.JTextField tJurusan;
    private javax.swing.JTextField tKelas;
    // End of variables declaration//GEN-END:variables
}
